spring:
  profiles:
    active: neon
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  banner:
    location: classpath:banner.txt

mybatis:
  mapper-locations: classpath*:sql/**/*.xml
  type-aliases-package: playground.model.dto
  configuration:
    map-underscore-to-camel-case: true

sever:
  port: ${PORT:8080}

app:
  version: "0.0.1"